site_name: Sepsis Tutorials
site_description: Tutorials for analysing bacterial omics data
site_author: Torsten Seemann, Anna Syme
site_favicon: favicon.ico
theme: united
markdown_extensions:
    - admonition
    - smarty
    - tables
extra_css:
    - css/sepsis.css
pages:
- Home: index.md
- Workshops:
    - Comparative Genomics:
        - Intro to Galaxy: workshop/genomics/1a/index.md
        - Intro to Artemis: workshop/genomics/1b/index.md
        - Assembly with Spades: workshop/genomics/2a/index.md
        - Annotation with Prokka: workshop/genomics/2b/index.md
        - Comparative genomics: workshop/genomics/3/index.md
    - Variant calling: workshop/snps/index.md
    - Phylogenetic trees: workshop/trees/index.md
    - Differential gene expression: workshop/dge/index.md
- Data:
    - Getting and moving data: data/data_access.md
    - File formats: data/file_formats.md
    - Genomics: dna/data.md
    - Transcriptomics: rna/data.md
    - Proteomics: pro/data.md
    - Metabolomics: met/data.md
- Tools:
    - Genomics:
        - Quality Control:
            - Overview: dna/qualitycontrol/qc.md
            - FastQC: dna/qualitycontrol/fastqc.md
        - De novo assembly:
            - Spades: dna/denovo/spades.md
            - Megahit: dna/denovo/megahit.md
            - Velvet: dna/denovo/velvet.md
            - VelvetOptimiser: dna/denovo/vopt.md
            - PacBio SMRT portal: dna/denovo/pacbio.md
            - Galaxy-Spades: dna/denovo/galaxy-spades.md
        - Annotation:
            - Prokka: dna/anno/prokka.md
            - RAST: dna/anno/rast.md
            - GENIX: dna/anno/genix.md
            - EuGene: dna/anno/eugene.md
            - MEGAnnotator: dna/anno/megannotator.md
        - Variant finding:
            - Snippy: dna/snps/snippy.md
            - Galaxy: dna/snps/galaxy.md
        - Pan genome:
            - Roary: dna/pan/roary.md
            - OrthoMCL: dna/pan/orthomcl.md
            - Mauve: dna/pan/mauve.md
    - Transcriptomics:
        - Quality Control: rna/qc.md
        - De novo assembly:
            - Oases: rna/denovo/oases.md
            - Trinity: rna/denovo/trinity.md
            - StringTie: rna/denovo/stringtie.md
    - Proteomics:
        - The Data: pro/data.md
        - Quality Control: pro/qc.md
    - Metabolomics:
        - The Data: met/data.md
        - Quality Control: met/qc.md
- Viz:
    - Bandage: viz/bandage/index.md
    - JBrowse: viz/jbrowse/index.md
    - Phandango: viz/phandango/index.md
    - Degust: viz/degust/index.md
- Workflows:
  - De novo assembly: workflows/assembly.md
  - Genome annotation: workflows/annotation.md
  - Finding variants: workflows/variants.md
  - Differential gene expression: workflows/dge.md
- About: about.md
