site_name: Sepsis Tutorials
site_description: Tutorials for analysing bacterial omics data
site_author: Anna Syme, Torsten Seemann
site_favicon: favicon.ico
theme: yeti
#theme: alabaster
markdown_extensions:
    - admonition
    - smarty
    - tables
#    - markdown_include.include
extra_css:
    - css/sepsis.css
pages:
- Home: index.md
- Introductory:
    - Overview: modules/overview.md
    - Dataset: modules/data/index.md
    - Using Galaxy: modules/galaxy/index.md
    - Quality control: modules/fastqc/index.md
    - Read trimming: modules/trimmomatic/index.md
    - Genome assembly: modules/spades/index.md
    - Genome annotation: modules/prokka/index.md
    - Variant finding: modules/snippy/index.md
#- Advanced:
    #- Differential Gene Expression: intro/dge/index.md
    #- Pan genome: intro/roary/index.md
    #- Artemis: modules/artemis/index.md
    #- JBrowse: modules/jbrowse/index.md
- About: about/index.md
