site_name: Sepsis Tutorials
site_description: Tutorials for analysing bacterial omics data
site_author: Anna Syme, Torsten Seemann
site_favicon: favicon.ico
theme: yeti
#theme: united
markdown_extensions:
    - admonition
    - smarty
    - tables
    - markdown_include.include
extra_css:
    - css/sepsis.css
pages:
- Home: index.md
- Genomics:
    - Overview: genomics.md
    - Using Galaxy: modules/galaxy/index.md
    - Training dataset: modules/data-dna/index.md
    - Galaxy intro for McGill: modules/galaxy_mcgill/galaxy_start.md
    - Quality control: modules/fastqc/index.md
    #- Read trimming: modules/trimmomatic/index.md
    - Genome assembly: modules/spades/index.md
    - Genome annotation: modules/prokka/index.md
    - Variant finding: modules/snippy/index.md
#- Transcriptomics:
#  - Overview: modules/transcriptomics.md
#  - Dataset: modules/data-rna/index.md
#  #- Quality control: modules/fastqc/index.md
#  #- Read trimming: modules/trimmomatic/index.md
#  - Transcriptome assembly: modules/stringtie/index.md
#  - Differential gene expression: modules/dge/index.md
#- Advanced:
    #- Differential Gene Expression: intro/dge/index.md
    #- Pan genome: intro/roary/index.md
    #- Artemis: modules/artemis/index.md
    #- JBrowse: modules/jbrowse/index.md
- About: about/index.md
